import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header className="w-full border-b border-border">
          <nav className="flex w-full max-w-4xl mx-auto flex-row items-center justify-between px-8 py-4">
            <div className="text-lg font-semibold">LWE Cryptography</div>
            <div className="flex gap-4">
              <Link
                href="/"
                className="text-muted-foreground hover:text-foreground transition-colors font-medium"
              >
                Home
              </Link>
              <Link
                href="/encrypt"
                className="text-muted-foreground hover:text-foreground transition-colors font-medium"
              >
                Encrypt
              </Link>
            </div>
          </nav>
        </header>
        {children}
        <Toaster theme="dark" duration={2000} />
      </body>
    </html>
  );
}
